# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

debug: false

spring:
    #    cache:
    #        #cache-names: cache1,cache2 # Disable dynamic creation of Caches.
    #        caffeine:
    #            spec: maximumSize=10,expireAfterAccess=5s
    main:
        banner-mode: CONSOLE
        web-application-type: NONE
    output:
        ansi:
            enabled: detect
