# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
#
# "LOGBACK: No context given for c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy"
# caused by TimeBasedRollingPolicy#setTotalSizeCap -> ignore !

pattern:
    logback:
        console: "%date{HH:mm:ss.SSS} - %5level - [%20.-20thread] - %replace(%-40.-40logger{0}){' ', '.'} - %message%n"
        file: "%date{yyyy-MM-dd HH:mm:ss.SSS} - %5level - [%20.-20thread] - %replace(%-40.-40logger{0}){' ', '.'} - %message%n"
    log4j2:
        console: "%date{HH:mm:ss.SSS} - %5level - [%20.-20thread] - %replace{%-40.-40logger{0}}{ }{.} - %message%n"
        file: "%date{yyyy-MM-dd HH:mm:ss.SSS} - %5level - [%20.-20thread] - %replace{%-40.-40logger{0}}{ }{.} - %message%n"

logging:
    #  config: classpath:logback-default.xml
    #  config: classpath:log4j-default.xml
    level:
        root: INFO
        org.springframework: INFO
    path: ${user.home}/.java-apps/logs # -> logging.path
    #file: ${logging.path}/application.log # not allowed in YAML, see Workaround in Profile.
    file:
        max-history: 30
        max-size: 10MB
        total-size-cap: 1GB
    pattern:
        console: ${pattern.logback.console}
        file: ${pattern.logback.file}
    register-shutdown-hook: false

---

spring:
    profiles: default

# Workaround     
logging:
    file: ${logging.path}/application.log
