# TRACE, DEBUG, INFO, WARN, ERROR, OFF
org.slf4j.simpleLogger.defaultLogLevel = INFO
org.slf4j.simpleLogger.levelInBrackets = false
org.slf4j.simpleLogger.logFile = System.out
org.slf4j.simpleLogger.showLogName = false
org.slf4j.simpleLogger.showShortLogName = true
org.slf4j.simpleLogger.showThreadName = true
org.slf4j.simpleLogger.showDateTime = true
org.slf4j.simpleLogger.dateTimeFormat = HH:mm:ss:SSS
#org.slf4j.simpleLogger.dateTimeFormat = yyyy-MM-dd HH:mm:ss:SSS

org.slf4j.simpleLogger.log.de.freese.dependency.update.client = INFO
org.slf4j.simpleLogger.log.de.freese.dependency.update.version = INFO

org.slf4j.simpleLogger.log.jdk.httpclient.HttpClient = INFO
org.slf4j.simpleLogger.log.org.springframework.web.client.RestTemplate = INFO
org.slf4j.simpleLogger.log.com.jayway.jsonpath.internal.path.CompiledPath = INFO
